<?php
//devData.php contains credentials that should not be exposed on GitHub, so it's in .gitignore
// include('devData.php');
$orcid = "https://sandbox.orcid.org/oauth/authorize?client_id=";

$orcidConnectLink = $orcid .
$orcid_client_id .
'&response_type=code&scope=/authenticate&show_login=false&redirect_uri=' .
$orcid_redirect_uri;


?>

<fieldset id='orcid_data' class='section'>

<?php if ($orcid_researcher): ?>
    <?php if ($user->id() === $orcid_researcher->id()) :?>
    <a id="connect-orcid-link" class="button" href="">
        <img id="orcid-id-logo" src="https://orcid.org/sites/default/files/images/orcid_16x16.png" width='16' height='16' alt="ORCID logo"/>
        <?php echo $this->translate('Update your data from your ORCID profile'); ?>
    </a>
    <?php else: ?>
    <p><?php echo $this->translate('Only the ORCID iD owner may update data.')?></p>
    <?php endif; ?>
<?php else: ?>
    <?php if ($user->id() === $identity->id()) :?>
    <a id="connect-orcid-link" href="<?php echo $orcidConnectLink; ?>">
        <img id="orcid-id-logo" src="https://orcid.org/sites/default/files/images/orcid_16x16.png" width='16' height='16' alt="ORCID logo"/>
        <?php echo $this->translate('Create or Connect your ORCID iD'); ?>
    </a>
    <?php else: ?>
    <p><?php echo $this->translate('Only owner of the Omeka S account can connect to their ORCID iD.')?></p>
    <?php endif; ?>
    <?php echo $orcidConnectLink; ?>
<?php endif; ?>
</fieldset>